name: ming
description: Application for abandoned pets.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# todo: need policy for versioning
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Internal Packages for ming
  
  signin_form:
    path: packages/signin_form
  log:
    path: packages/log
  ming_api:
    path: packages/ming_api
  auth:
    path: packages/auth

  # For pretty & generalized logging
  loggy: ^2.0.1+1

  # Bloc pattern support
  flutter_bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  json_serializable: ^6.1.6
  extended_image: ^6.2.1
  firebase_core: ^1.17.0
  formz: ^0.4.0
  google_fonts: ^2.3.2
  font_awesome_flutter: ^9.1.0
  firebase_crashlytics: ^2.8.0
  go_router: ^5.0.5
  copy_with_extension: ^4.0.3
  loader_overlay: ^2.0.7
  flutter_spinkit: ^5.1.0
  uuid: ^3.0.6
  responsive_framework: ^0.2.0
  url_launcher: ^6.1.3
  share_plus: ^4.0.8
  expandable: ^5.0.1
  tuple: ^2.0.0
  google_maps_flutter: ^2.1.9
  google_maps_flutter_web: ^0.4.0+1
  html: ^0.15.0
  flutter_web_auth: ^0.4.1
  universal_html: ^2.0.8

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  bloc_test: ^9.0.3
  mocktail: ^0.2.0
  random_string: ^2.3.1
  firebase_auth: ^3.3.18
  copy_with_extension_gen: ^4.0.3

flutter:
  uses-material-design: true
  fonts:
    - family: MingIcons
      fonts:
        - asset: fonts/ming_icons/MingIcons.ttf
  assets:
  - assets/
  - assets/mocks/

flutter_intl:
  enabled: true
  main_locale: ko_KR
