name: ming
description: Application for abandoned pets.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# todo: need policy for versioning
version: 0.0.1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  json_serializable: ^6.1.6
  extended_image: ^6.0.2+1
  firebase_core: ^1.17.0
  authentication_repository:
    path: packages/authentication_repository
  signin_form:
    path: packages/signin_form
  formz: ^0.4.0
  google_fonts: ^2.3.2
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  bloc_test: ^9.0.3
  mocktail: ^0.2.0
  random_string: ^2.3.1
  firebase_auth: ^3.3.18

flutter:
  uses-material-design: true
  assets:
  - assets/

flutter_intl:
  enabled: true
  main_locale: ko_KR
