// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjJJ3dD6beY6rQo94_zyEgD30lBNUuwUc',
    appId: '1:712319796217:web:287b14c3e83e727c0fb328',
    messagingSenderId: '712319796217',
    projectId: 'ming-6dd75',
    authDomain: 'ming-6dd75.firebaseapp.com',
    databaseURL: 'https://ming-6dd75-default-rtdb.firebaseio.com',
    storageBucket: 'ming-6dd75.appspot.com',
    measurementId: 'G-Z3TXLW48VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0nDOvyZT9jOTkXdMlsdSODipzY4qnG6E',
    appId: '1:712319796217:android:77e990c2cd4cc4020fb328',
    messagingSenderId: '712319796217',
    projectId: 'ming-6dd75',
    databaseURL: 'https://ming-6dd75-default-rtdb.firebaseio.com',
    storageBucket: 'ming-6dd75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrX0Vt4q9Nqq-5GsJeX1RRHxoQHXMY8LE',
    appId: '1:712319796217:ios:6ec7e1e27dfc24e00fb328',
    messagingSenderId: '712319796217',
    projectId: 'ming-6dd75',
    databaseURL: 'https://ming-6dd75-default-rtdb.firebaseio.com',
    storageBucket: 'ming-6dd75.appspot.com',
    iosClientId: '712319796217-viqi1s7iaugee9frg2afe64onr5nijeo.apps.googleusercontent.com',
    iosBundleId: 'com.ming.ming',
  );
}
