name: Basic build & Unit test for pull request.

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  android_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          cache: true
      - run: dart pub global activate melos
      - run: sudo apt-get install lcov
      - run: melos bootstrap
      - run: melos test
      - run: melos analyze
      - run: flutter build apk
      - run: flutter build appbundle

  ios_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          cache: true
          architecture: x64
      - run: dart pub global activate melos
      - run: brew install lcov
      - run: melos bootstrap
      - run: melos test
      - run: melos analyze
      - run: flutter build ios --release --no-codesign

  web_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          cache: true
      - run: dart pub global activate melos
      - run: sudo apt-get install lcov
      - run: melos bootstrap
      - run: melos test
      - run: melos analyze
      - run: flutter build web

      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage_report
